name = (input("What is your name? "))
act = (input("Ok. Now enter an action: "))
print()
print("I'm sorry, " + name + ". I'm afraid I can't do that.")
print("(The action \"" + act + "\" was not performed.)")
