restName = input("Restaurant name? ")
entreeOne = input("First entree? ")
entreeOnePrice = input("First entree price? ")
entreeTwo = input("Second entree? ")
entreeTwoPrice = input("Second entree price? ")
entreeThree = input("Third entree? ")
entreeThreePrice = input("Third entree price? ")
print()
print("1234567890123456789012345678901234567890")
print()
print(restName + " Entrees")
print("-" * len(restName + " Entrees"))
print(entreeOne + ("." * (36 - len(entreeOne))) + '$' + (" " * (3 - (len(entreeOnePrice)))) + str(entreeOnePrice))
print(entreeTwo + ("." * (36 - len(entreeTwo))) + '$' + (" " * (3 - (len(entreeTwoPrice)))) + str(entreeTwoPrice))
print(entreeThree + ("." * (36 - len(entreeThree))) + '$' + (" " * (3 - (len(entreeThreePrice)))) + str(entreeThreePrice))